%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: X:\Sherlab\0harmonization\Jordan\OptwithSF\behavbysex\N3_optimize_dataUPDATED.xls
%    Worksheet: data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/09/14 12:01:58

%% Import the data
[~, ~, raw] = xlsread('X:\Sherlab\0harmonization\Jordan\OptwithSF\behavbysex\N3_optimize_dataUPDATED.xls','data','A2:AF36310');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
N3optimizedataUPDATED = table;

%% Allocate imported array to column variable names
NAGE = data(:,1);
NSEX = data(:,2);
NEDUC = data(:,3);
N2AQ2 = data(:,4);
N2AQ3 = data(:,5);
idnum = data(:,6);
nethrace = data(:,7);
VARUNIT = data(:,8);
VARSTRAT = data(:,9);
AUDWEIGHT = data(:,10);
tolpy = data(:,11);
cutdpy = data(:,12);
morelngpy = data(:,13);
lotspy = data(:,14);
giveuppy = data(:,15);
hprobpy = data(:,16);
cravepy = data(:,17);
withdrpy = data(:,18);
rolintpy = data(:,19);
hazpy = data(:,20);
sprobpy = data(:,21);
totaudrpy = data(:,22);
maxdrinks = data(:,23);
drinkfreq = data(:,24);
usualamt = data(:,25);
freqmax = data(:,26);
binge = data(:,27);
intox = data(:,28);
freqex = data(:,29);
hlth_probs = data(:,30);
sf_nonagebias = data(:,31);
behav = data(:,32);

%% Clear temporary variables
clearvars data raw R;